name: grainlegumes-pino
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.4
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - pyarrow
  - ipykernel
  - ipywidgets
  - ipython
  - pip
  - pip:
      - neuraloperator==2.0.*
      - wandb
      - optuna